# Generated by Django 3.0.7 on 2020-10-28 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Xray', 'Xray')], default='Xray', max_length=50)),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescriptionid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('clinicname', models.CharField(max_length=20)),
                ('jobstatus', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=20)),
                ('prescriptionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Prescription')),
            ],
        ),
        migrations.CreateModel(
            name='MedicinesPrescribed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdosage', models.IntegerField()),
                ('mduration', models.CharField(max_length=20)),
                ('mname', models.CharField(max_length=20)),
                ('prescriptionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Prescription')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicaltest', models.CharField(max_length=20)),
                ('prescriptionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Prescription')),
            ],
        ),
    ]
