# Generated by Django 3.0.7 on 2020-10-31 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0019_description_medicaltest_medicinesprescribed_prescription_receptionist_symptoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='receptionist',
            old_name='rid',
            new_name='receptionistid',
        ),
        migrations.AddField(
            model_name='description',
            name='recimage',
            field=models.ImageField(blank=True, null=True, upload_to='recordimages/'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, max_length=1)),
                ('age', models.IntegerField()),
                ('Bname', models.CharField(blank=True, max_length=30)),
                ('Sname', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('pincode', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescribedIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.IntegerField()),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Appointment')),
                ('prescriptionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Prescription')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='description',
            name='rid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital.Records'),
            preserve_default=False,
        ),
    ]
